parameters:
#    newi_core.example.class: NEWI\CoreBundle\Example

services:
#    newi_core.example:
#        class: %newi_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
